/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

/**
 *
 * @author laboratorio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmenuBar = new javax.swing.JMenuBar();
        jMenuAutor = new javax.swing.JMenu();
        jItemcadastrarAutor = new javax.swing.JMenuItem();
        jItemEditarAutor = new javax.swing.JMenuItem();
        jMenuLivro = new javax.swing.JMenu();
        jmenucadastrarLivro = new javax.swing.JMenuItem();
        jmenuEditarLivro = new javax.swing.JMenuItem();
        jmenuTabelas = new javax.swing.JMenu();
        jTblLivro = new javax.swing.JMenuItem();
        jTblAutor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuAutor.setText("Autor");

        jItemcadastrarAutor.setText("Cadastrar Autor");
        jItemcadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemcadastrarAutorActionPerformed(evt);
            }
        });
        jMenuAutor.add(jItemcadastrarAutor);

        jItemEditarAutor.setText("Editar e Excluir Autor");
        jItemEditarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEditarAutorActionPerformed(evt);
            }
        });
        jMenuAutor.add(jItemEditarAutor);

        jmenuBar.add(jMenuAutor);

        jMenuLivro.setText("Livro");

        jmenucadastrarLivro.setText("Cadastrar Livro");
        jmenucadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenucadastrarLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jmenucadastrarLivro);

        jmenuEditarLivro.setText("Editar e Excluir Livro");
        jmenuEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEditarLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jmenuEditarLivro);

        jmenuBar.add(jMenuLivro);

        jmenuTabelas.setText("Tabelas");

        jTblLivro.setText("Tabela Livros");
        jTblLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTblLivroActionPerformed(evt);
            }
        });
        jmenuTabelas.add(jTblLivro);

        jTblAutor.setText("Tabela Autores");
        jTblAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTblAutorActionPerformed(evt);
            }
        });
        jmenuTabelas.add(jTblAutor);

        jmenuBar.add(jmenuTabelas);

        setJMenuBar(jmenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemcadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemcadastrarAutorActionPerformed
        CadastrarAutor cadAutor = new CadastrarAutor();
        cadAutor.setVisible(true);
    }//GEN-LAST:event_jItemcadastrarAutorActionPerformed

    private void jItemEditarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEditarAutorActionPerformed
        EditarEExcluirAutor a = new EditarEExcluirAutor();
        a.setVisible(true);
    }//GEN-LAST:event_jItemEditarAutorActionPerformed

    private void jmenucadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenucadastrarLivroActionPerformed
        CadastrarLivro c = new CadastrarLivro();
        c.setVisible(true);
    }//GEN-LAST:event_jmenucadastrarLivroActionPerformed

    private void jmenuEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEditarLivroActionPerformed
        EditarEExcluirLivro e = new EditarEExcluirLivro();
        e.setVisible(true);
    }//GEN-LAST:event_jmenuEditarLivroActionPerformed

    private void jTblLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTblLivroActionPerformed
        TabelaLivro tabelaLivro = new TabelaLivro();
        tabelaLivro.setVisible(true);
    }//GEN-LAST:event_jTblLivroActionPerformed

    private void jTblAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTblAutorActionPerformed
        TabelaAutor tbl = new TabelaAutor();
        tbl.setVisible(true);
    }//GEN-LAST:event_jTblAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemEditarAutor;
    private javax.swing.JMenuItem jItemcadastrarAutor;
    private javax.swing.JMenu jMenuAutor;
    private javax.swing.JMenu jMenuLivro;
    private javax.swing.JMenuItem jTblAutor;
    private javax.swing.JMenuItem jTblLivro;
    private javax.swing.JMenuBar jmenuBar;
    private javax.swing.JMenuItem jmenuEditarLivro;
    private javax.swing.JMenu jmenuTabelas;
    private javax.swing.JMenuItem jmenucadastrarLivro;
    // End of variables declaration//GEN-END:variables
}
